# Generated by Django 5.1.6 on 2025-03-19 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CrashGame",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("server_seed", models.CharField(max_length=64, unique=True)),
                (
                    "client_seed",
                    models.CharField(default="default_client_seed", max_length=64),
                ),
                ("hashed_server_seed", models.CharField(max_length=64)),
                ("nonce", models.IntegerField(default=0)),
                ("crash_point", models.FloatField(default=1.0)),
                ("game_running", models.BooleanField(default=False)),
            ],
        ),
    ]
