# Generated by Django 5.1.6 on 2025-04-04 10:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crash", "0002_crashgame_users_crashgameuser"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="crashgame",
            name="users",
            field=models.ManyToManyField(
                related_name="crash_games", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
