# Generated by Django 5.1.6 on 2025-04-04 10:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RouletteGame",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("server_seed", models.CharField(max_length=64, unique=True)),
                (
                    "client_seed",
                    models.CharField(default="default_client_seed", max_length=64),
                ),
                ("hashed_server_seed", models.CharField(max_length=64)),
                ("nonce", models.IntegerField(default=0)),
                ("game_running", models.BooleanField(default=False)),
                ("number", models.IntegerField()),
                ("outcome", models.CharField(default="red", max_length=64)),
                (
                    "users",
                    models.ManyToManyField(
                        related_name="roulette_games", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RouletteGameUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bet_amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="players",
                        to="roulette.roulettegame",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
